# Generated by Django 4.1 on 2023-03-22 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=50)),
                ("customer_email", models.EmailField(max_length=100)),
                ("customer_mobile", models.CharField(max_length=50)),
                ("customer_address", models.CharField(max_length=50)),
                ("customer_date", models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usernameL", models.CharField(max_length=50)),
                ("passwordL", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(default="customer0@gmail.com", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=50, unique=True)),
                (
                    "stock_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("stock_quantity", models.CharField(max_length=50)),
                ("stock_total", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        default="photos/1/1/2001/standardimg.png",
                        upload_to="photos/%y/%m/%d",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("createdAcc", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-createdAcc"],
            },
        ),
    ]
