# Generated by Django 4.1.7 on 2023-03-24 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('company_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_mobile',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_date',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stock_price',
        ),
        migrations.AddField(
            model_name='customer',
            name='EnterDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stocks',
            name='close_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stocks',
            name='high_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='low_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='open_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='ticker',
            field=models.CharField(default='tik1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_quantity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_price', models.FloatField(default=0.0)),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.stocks')),
            ],
        ),
    ]
